# Generated by Django 4.2.7 on 2026-03-14 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_mapping', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_product_mappings', to='product.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_product_mappings', to='vendor.vendor')),
            ],
            options={
                'verbose_name': 'Vendor-Product Mapping',
                'verbose_name_plural': 'Vendor-Product Mappings',
                'db_table': 'vendor_product_mapping',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['vendor', 'is_active'], name='vpm_vendor_active_idx'), models.Index(fields=['product', 'is_active'], name='vpm_product_active_idx')],
                'unique_together': {('vendor', 'product')},
            },
        ),
    ]
