# Generated by Django 4.2.7 on 2026-03-14 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCourseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_mapping', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_course_mappings', to='course.course')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_course_mappings', to='product.product')),
            ],
            options={
                'verbose_name': 'Product-Course Mapping',
                'verbose_name_plural': 'Product-Course Mappings',
                'db_table': 'product_course_mapping',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['product', 'is_active'], name='pcm_product_active_idx'), models.Index(fields=['course', 'is_active'], name='pcm_course_active_idx')],
                'unique_together': {('product', 'course')},
            },
        ),
    ]
