# Generated by Django 4.2.7 on 2026-03-14 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certification', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCertificationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_mapping', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_certification_mappings', to='certification.certification')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_certification_mappings', to='course.course')),
            ],
            options={
                'verbose_name': 'Course-Certification Mapping',
                'verbose_name_plural': 'Course-Certification Mappings',
                'db_table': 'course_certification_mapping',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['course', 'is_active'], name='ccm_course_active_idx'), models.Index(fields=['certification', 'is_active'], name='ccm_cert_active_idx')],
                'unique_together': {('course', 'certification')},
            },
        ),
    ]
